# Generated by Django 5.0.2 on 2024-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regarding', models.CharField(blank=True, max_length=255, null=True, verbose_name='Betreff')),
                ('full_name', models.CharField(blank=True, default='Unknown', max_length=255, null=True, verbose_name='Namen angeben')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='Metteilung')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'user_notice',
            },
        ),
    ]
